name: greeting

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Журавлев Данил Владимирович студент группы БО241ИСТ

      - name: Run a multi-line script
        run: |
          echo Дальневосточный государственный университет путей сообщения
          echo Институт транспортных и энергетических систем
          echo Цифровая индустрия и защита информации
